#!/usr/bin/env python3

import argparse
from datetime import datetime
from enum import Enum
import getpass
import json
import logging
import requests
from requests.exceptions import Timeout
import signal
import sys
import time

class State(Enum):
    """
    Current program state. Syncing means we're waiting for cards to be tuned to
    the specified channel, Collecting means the cards are tuned and we're counting
    frames
    """
    Syncing = 1,
    Collecting = 2

class SourceInfo:
    """
    This object stores information about a data source we're tracking
    """
    name = ""       # The name of this data source
    uuid = 0        # Kismet's UUID for this data source
    count = 0       # The number of frames observed by this data source
    last_count = 0  # The previous number of frames observed by this data source
    offset = 0      # Frame count offset (to account for sync time)
    hardware = ""

def http_get(uri, timeout=5, retries=1):
    """
    This function attempts to retrieve the specified URI using an HTTP GET
    request.

    timeout -- The HTTP request will wait up to this number of seconds for
               a response
    retries -- If the HTTP GET fails, it will be retried up to the specifiedo
               number of times
    """
    logging.info(f"Making GET request to {uri}")

    attempt = 0
    while attempt <= retries:
        start = time.time()

        response = None
        try:
            response = session.get(uri, timeout=timeout)

        except Timeout:
            logging.error(f"HTTP GET timed out (timeout was set to {timeout} sec)")
            attempt += 1

        except Exception as e:
            logging.error("HTTP GET failed for {} with exception: {}".format(uri, e))
            sys.exit(1)

        else:
            end = time.time()
            elapsed = end - start
            logging.info("Request took {0:.3f} seconds".format(elapsed))
            break

    if attempt == retries:
        logging.error(f"Too many timeouts ({attempt}) for HTTP GET")
        sys.exit(1)

    return response

def http_post(uri, post_data, timeout=5):
    """
    This function attempts to make an HTTP POST to the specified URI

    timeout -- The HTTP request will wait up to this number of seconds for
               a response
    """
    logging.info(f"Making POST request to {uri}")

    start = time.time()

    if post_data == None:
        post_data = ""

    #print(post_data)
    response = None
    try:
        response = session.post(uri, data=post_data, timeout=timeout)

    except Exception as e:
        logging.error("HTTP POST failed for {} with exception: {}".format(uri, e))
        sys.exit(1)

    end = time.time()
    elapsed = end - start
    logging.info("HTTP POST to {0} took {1:.3f} seconds".format(uri, elapsed))

    return response

def kis_get_bool(uri):
    """
    This function performs an HTTP GET for the specified URI, and returns True
    or False depending on the response code.
    """
    actual_uri = f"{base_uri}{uri}"
    response = http_get(actual_uri)

    if response.status_code == 200:
        return True
    else:
        return False

def kis_get_json(uri):
    """
    This function GETs the specified URI, expecting a JSON response.
    The JSON response is formatted into a python dictionary and returned.
    """
    actual_uri = f"{base_uri}{uri}"
    response = http_get(actual_uri)

    if response.status_code != 200:
        logging.error(f"HTTP GET failed for {actual_uri}")
        sys.exit(1)

    json_result = response.content.decode('utf-8')
    dict_result = json.loads(json_result)
    return dict_result

def kis_post_cmd(uri, obj):
    """
    Post the specified REST API command to the Kismet server

    See: https://www.kismetwireless.net/docs/devel/webui_rest/commands/

    uri -- The (relative) uri for the destination API endpoint
    obj -- A dictionary representing the command to post
    """
    actual_uri = f"{base_uri}{uri}"
    post_data = json.dumps(obj)
    post_data = {
            "json": post_data
        }

    response = http_post(actual_uri, post_data)

    if response.status_code != 200:
        logging.error(f"Kismet command failed for {uri} with status {response.status_code}")
        return False

    return True

def kis_get_sources():
    """
    Return a dictionary of all available datasources on the kismet server
    """
    url = f"/datasource/all_sources.json"
    return kis_get_json(url)

def kis_get_interfaces():
    """
    Return a dictionary of all available interfaces on the kismet server
    """
    url = f"/datasource/list_interfaces.json"
    return kis_get_json(url)

def kis_check_session():
    return kis_get_bool("/session/check_session")

def kis_have_source(source_name):
    """
    This function determines whether the specified datasource is known to
    the Kismet server

    Arguments:
    source_name -- The name of a datasource to look for
    """
    sources = kis_get_sources()
    for source in sources:
        if source['kismet.datasource.name'] == source_name:
            return True
    
    return False

def kis_add_source(interface_name):
    """
    This function adds the specified interface as a datasource

    Arguments:
    interface_name -- The name of an interface to look for
    """
    logging.info(f"Adding datasource {interface_name}")

    cmd = {
        "definition": interface_name
    }

    kis_post_cmd("/datasource/add_source.cmd", cmd)

def kis_have_interface(interface_name):
    """
    This function determines whether the specified interface is known to
    the Kismet server

    Arguments:
    interface_name -- The name of an interface to look for
    """
    interfaces = kis_get_interfaces()
    for interface in interfaces:
        if interface['kismet.datasource.probed.interface'] == interface_name:
            return True

    return False

def kis_set_channel(uuid, channel):
    logging.info(f"Setting channel for datasource {uuid} to {channel}")

    cmd = {
        "channel": channel
    }

    result = kis_post_cmd(f"/datasource/by-uuid/{uuid}/set_channel.cmd", cmd)
    
    if not result and not ignore_chan_err:
        logging.error("Failed to set channel for uuid {uuid}")
        sys.exit(1)

def get_max(sources_by_name):
    max_packets = 0

    for source_name, source in sources_by_name.items():
        if source.count > max_packets:
            max_packets = source.count

    return max_packets

def signal_handler(sig, frame):
    if sig == signal.SIGINT:
        print("Caught SIGINT")
        sys.exit(0)

# Extend ArgumentParser to override the error function
class CustomArgumentParser(argparse.ArgumentParser):
    def error(self, message):
        self.print_help()
        sys.stderr.write("\nNote: Kismet must be running for shootout to work!\n\n")
        sys.exit(2)

if __name__ == "__main__":

    # Configure logging
    FORMAT = '[%(asctime)-15s %(levelname)s] %(message)s'
    #logging.basicConfig(stream=sys.stdout, format=FORMAT, level=logging.INFO)
    logger = logging.getLogger()
    logger.propagate = False

    # Register signal handler for SIGINT (CTRL+C) 
    signal.signal(signal.SIGINT, signal_handler)

    sources_by_name = dict()

    parser = CustomArgumentParser(description="Kismet datasource shootout")
    parser.add_argument("sources", metavar="SRC", nargs="+",
            help="data sources to use in the shootout (e.g. wlan0)")
    parser.add_argument("-c", dest="channel", required=True,
            help="the channel to monitor")
    parser.add_argument("-l", dest="log", action="store_true",
            help="log diagnostic data to shootout.log")
    parser.add_argument("-u", dest="user",
            help="a user name to log into Kismet with")
    parser.add_argument('-P', '-p', dest="password",
            help="a password to log into Kismet with")
    parser.add_argument("-s", dest="server", default="localhost",
            help="ip/hostname of kismet server (defaults to localhost")
    parser.add_argument("-x", dest="ignore_chan_err",
            help="Ignore errors while switching channels")

    # Process command-line arguments
    args = parser.parse_args()

    username = ""
    if args.user:
        username = args.user

    password = ""
    if args.password:
        password = args.password
    else:
        password = getpass.getpass()

    if args.log:
        logging.basicConfig(filename='shootout.log', format=FORMAT, level=logging.INFO)
        logger.propagate = False

    # Configure HTTP client session
    session = requests.Session()
    session.auth = (username, password)

    # URI for accessing Kismet
    base_uri = "http://{}:2501".format(args.server)
    print("Connecting to Kismet Server {}".format(base_uri))

    # If true, ignore channel switching errors
    ignore_chan_err = False
    if args.ignore_chan_err:
        ignore_chan_err = True

    # Verify login
    if not kis_check_session():
        print("Invalid login")
        sys.exit(1)
    else:
        print("Logged in!")

    # Configure datasources
    for source_name in args.sources:
        logging.info(f"Checking for datasource named {source_name}")

        if not kis_have_source(source_name):
            logging.info(f"Source {source_name} not found")
            logging.info(f"Checking for interface named {source_name}")
            if not kis_have_interface(source_name):
                logging.warning(f"No interface named {source_name}, ignoring")
                continue

            # Add the interface as a datasource
            logging.info(f"Interface {source_name} found, adding as a datasource")
            kis_add_source(source_name)

        else:
            logging.info(f"Source found")

        si = SourceInfo()
        si.name = source_name
        sources_by_name[source_name] = si

    # Make sure some data sources were configured
    if len(sources_by_name) == 0:
        logging.error("No sources configured, exiting")
        sys.exit(1)

    # Update data source UUIDs
    datasources = kis_get_sources()
    for ds in datasources:
        name = ds['kismet.datasource.name']
        if name in sources_by_name:
            sources_by_name[name].uuid = ds['kismet.datasource.uuid']
            sources_by_name[name].hardware = ds['kismet.datasource.hardware']

    # Tune data sources to the specified channel
    state = State.Syncing
    for source_name, source in sources_by_name.copy().items():
        print("Tuning data source {} to channel {}".format(source_name, args.channel))
        kis_set_channel(source.uuid, args.channel)

    while True:

        # Check that our session is still valid
        if not kis_check_session():
            logging.warning("Session check failed")
            # TODO: implement "__update_session" functionality

        datasources = kis_get_sources()

        if state == State.Syncing:
            # Syncing means we're waiting for all of the cards to tune to 
            # the specified channel

            all_tuned = True

            # Check whether all the sources have tuned
            for ds in datasources:
                ds_name = ds['kismet.datasource.name']
                ds_chan = ds['kismet.datasource.channel']

                # Is this a source we care about?
                if ds_name in sources_by_name:

                    # Has this card tuned yet?
                    if (ds_chan == args.channel) or ignore_chan_err:
                        # Yes, update its offset
                        sources_by_name[ds_name].offset = ds['kismet.datasource.num_packets']
                        print("Offset for {} = {}".format(ds_name, sources_by_name[ds_name].offset))
                    else:
                        all_tuned = False

            if all_tuned:
                # All sources have tuned to the specified channel
                state = State.Collecting

                # Make note of the start of collection time
                start_time = datetime.now()
            
        elif state == State.Collecting:
            # Collecting means all the cards are tuned and we can start
            # recording packet counters

            print('\x1bc')
            
            # Print a column header
            print("Source          Hardware       PPS     Packets        RX %")
            print("----------------------------------------------------------")

            # Update packet counters
            for ds in datasources:
                ds_name = ds['kismet.datasource.name']
                ds_count = ds['kismet.datasource.num_packets']

                # Is this a source we care about?
                if ds_name in sources_by_name:

                    # Yup, update packet counter
                    sources_by_name[ds_name].last_count = sources_by_name[ds_name].count
                    sources_by_name[ds_name].count = ds_count - sources_by_name[ds_name].offset

            max_count = get_max(sources_by_name)
            if max_count == 0: max_count = 1

            for source_name, source in sources_by_name.items():
                #print("{} {} ({:.2%})".format(ifc, count, count / max_count))
                color = ''
                percent = source.count / max_count
                #colors by percent
                if percent < .75:
                    color = '\033[91m'
                elif percent < .90:
                    color = '\033[93m'
                elif percent == 1:
                    color = '\033[7;94m'
                else:
                    color = '\033[94m'
                #highlight failures in red
                if ( source.count - source.last_count ) < 1:
                    color = '\033[91m'
                print("{}{:<16}{:<12}{:>6}{:>12}{:>12.2%}\033[0m".format(
                    color,
                    source_name,
                    source.hardware,
                    source.count - source.last_count,
                    source.count,
                    percent))

            time_delta = datetime.now() - start_time
            m, s = divmod(int(time_delta.total_seconds()), 60)
            h, m = divmod(m, 60)
            print("\nElapsed time on channel {}: {} Hours {} Minutes {} Seconds".format(args.channel, h, m, s))

        else:
            print("State error")
            sys.exit(1)

        time.sleep(1)

